Week 01
green-fox-academy/vulpes-tribes-backend pull request #12
Opened 2018-12-14 09:51 UTC by Organt

2018-12-14 10:34 UTC, OndraSlejtr reviewed
Change project structure - packages should follow Google Java styleguide.

2018-12-14 10:34 UTC, Cyn1que commented on src/main/java/com/tribes_backend/tribes/tribesUser/OKStatusService/OKResponseMethods.java
> +public class OKResponseMethods {
Remove / replace with other validation responses.

2018-12-14 10:34 UTC, Cyn1que commented on src/main/java/com/tribes_backend/tribes/tribesUser/OKStatusService/OKResponseModel.java
> +package com.tribes_backend.tribes.tribesUser.OKStatusService;
Remove / replace with other validation responses.

2018-12-14 10:34 UTC, Cyn1que commented on src/main/java/com/tribes_backend/tribes/tribesUser/errorService/ErrorResponseModel.java
> +}
Add newline

2018-12-14 10:34 UTC, Cyn1que commented on src/main/java/com/tribes_backend/tribes/tribesUser/errorService/ErrorResponseModel.java
> +/*import lombok.AllArgsConstructor;
Remove

2018-12-14 10:34 UTC, Cyn1que commented on src/main/java/com/tribes_backend/tribes/tribesUser/model/UserModelHelpersMethods.java
> +
Remove extra blank lines

2018-12-14 10:34 UTC, Cyn1que commented on src/main/java/com/tribes_backend/tribes/tribesUser/repository/UserTRepository.java
> +@Service
@Repository

2018-12-14 10:34 UTC, Cyn1que commented on src/main/java/com/tribes_backend/tribes/tribesUser/repository/UserTRepository.java
> +    TribesUser findByUsername(String username);
Should return Optional\<TribesUser\> instead of TribesUser

2018-12-14 10:34 UTC, Cyn1que commented on src/main/java/com/tribes_backend/tribes/tribesUser/service/UserCrudService.java
> +    public boolean save(TribesUser newUser) {
Make it return void and throw exception in case saving fails.

2018-12-14 10:34 UTC, Cyn1que commented on src/main/resources/application.properties
> +spring.flyway.url =  ${FLYWAY_URL}
Should use ${DATASOURCE_URL}

2018-12-14 10:34 UTC, Cyn1que commented on src/main/resources/application.properties
> +server.port = 8090
Solve the issue of using env variables for port number as well.

2018-12-14 10:34 UTC, Cyn1que commented on src/test/java/com/tribes_backend/tribes/TestKingdom.java
> +        assertEquals(null, kingdom.getName());
Test for annotation validation from Kingdom model (test for @NotNull etc).

2018-12-14 10:34 UTC, Cyn1que commented on src/test/java/com/tribes_backend/tribes/tribesUser/controller/UserRestControllerTest.java
> +}
Add newline

2018-12-17 12:35 UTC, Cyn1que commented on src/main/java/com/tribes_backend/tribes/tribesUser/service/UserCrudService.java
> +    public boolean save(TribesUser newUser) {
@Organt

2018-12-17 12:35 UTC, Cyn1que commented on src/main/resources/application.properties
> +spring.flyway.url =  ${FLYWAY_URL}
@PeterXMR

2018-12-18 09:51 UTC, OndraSlejtr requested changes

2018-12-18 12:40 UTC, Kopsova commented on src/main/java/com/tribesbackend/tribes/tribesuser/model/UserModelHelpersMethods.java
> +        if (tribesUser.getUsername() == null || tribesUser.getPassword() == null) {
Done. Merged still to week-01

2019-01-15 10:13 UTC, adamgyulavari requested changes

2019-01-15 10:13 UTC, adamgyulavari commented on src/test/java/com/tribesbackend/tribes/tribesuser/controller/UserRestControllerTest.java
> +//                "}";
@Organt remove outcommented code

2019-01-22 14:33 UTC, closed without merging